// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecmwlutgcezdgndosiac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbXdsdXRnY2V6ZGduZG9zaWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1OTk0NjIsImV4cCI6MjA1MjE3NTQ2Mn0.FHJzmyVxxMJZZezG0-4eLCkguVoD_LNuXdNOjEvNSek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);